PROJECT_TAR=commons-configuration-2.5-RC1.tar.gz
PROJECT_WWW=https://github.com/apache/commons-configuration/archive/$(PROJECT_TAR)
PROJECT_DIR=build/commons-configuration-commons-configuration-2.5-RC1
PKG_NAME=org.apache.commons.configuration2
JAR_NAME=commons-configuration2-2.5.jar
TEST_PATH=$(PROJECT_DIR)src/test/
