PROJECT_TAR=1.18-RC1.tar.gz
PROJECT_WWW=https://github.com/apache/commons-compress/archive/$(PROJECT_TAR)
PROJECT_DIR= build/commons-compress-1.18-RC1/
PKG_NAME=org.apache.commons.compress
JAR_NAME=commons-compress-1.18.jar
TEST_PATH=$(PROJECT_DIR)src/test/
