PROJECT_TAR=LANG_3_8_RC1.tar.gz
PROJECT_WWW=https://github.com/apache/commons-lang/archive/$(PROJECT_TAR)
PROJECT_DIR=build/commons-lang-LANG_3_8_RC1
PKG_NAME=org.apache.commons.lang3
JAR_NAME=commons-lang3-3.8.jar
TEST_PATH=$(PROJECT_DIR)src/test/
